### ISSUE TITLE
add the repo to https://github.com/nichtdax/awesome-totally-open-chatgpt

### ISSUE THREAD

**Issue by alreadydone** [clue-ai/ChatYuan#25]
https://github.com/nichtdax/awesome-totally-open-chatgpt#readme

**Comment by yhyu13** [comment]
@alreadydone nice

**Comment by alreadydone** [comment]
resolved by https://github.com/nichtdax/awesome-totally-open-chatgpt/commit/50ee7e28fc5fc309eabd3d9b156effb11459cb9d
