### ISSUE TITLE
真的，建议不要再发广告了

### ISSUE THREAD

**Issue by AtaraxiaZ** [clue-ai/ChatYuan#3]
起码先做点真东西出来再宣传，放github上更是让外国人看我们笑话
![image](https://user-images.githubusercontent.com/40316526/217232608-90b14fd4-39ff-4351-9387-5c32834ef20e.png)

**Comment by joytianya** [comment]
数学能力还是比较薄弱的，再接再厉

**Comment by xxllp** [comment]
这个看来只能算是各粗糙品，连半成品都不能算
