### ISSUE TITLE
[finetune] 请问下如果从t5模型微调训练出ChatYuan-large-v1模型

### ISSUE THREAD

**Issue by Tian14267** [clue-ai/ChatYuan#44]
大神们好，我想咨询一下，如何从**t5**模型（如`t5-large`），微调训练出你们的`ChatYuan-large-v1`和`ChatYuan-large-v2`模型？我直接替换预训练模型为原始的t5模型，训练出的结果都是乱码。请问能否指点一下啊

**Comment by joytianya** [comment]
ChatYuan-large-v1和ChatYuan-large-v2 元语智能基于t5架构重0训练的模型，不是google发布的t5模型

**Comment by Tian14267** [comment]
> ChatYuan-large-v1和ChatYuan-large-v2 元语智能基于t5架构重0训练的模型，不是google发布的t5模型

相应的**预训练模型**也是重新训练的嘛？请问这个你们有开源，能学习一下吗

**Comment by joytianya** [comment]
是的，这个可以参考google t5（他们写的很详细了）, 在readme里也有相应的链接
