### ISSUE TITLE
怎样离线使用这个程序？

### ISSUE THREAD

**Issue by a0ge0a** [clue-ai/ChatYuan#45]
模型离线加载成功不了，总报FileNotFoundError: configuration file<config.json> or <model_config.json> not found。但是这个文件我本地都下载好了，[2023-04-18 10:32:01,126] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/ChatYuan-large-v2/added_tokens.json> not exist 还有这个离线运行的话也会报错

**Comment by joytianya** [comment]
你下载的是paddle版本？

**Comment by a0ge0a** [comment]
是的，应该用哪个版本呀

**Comment by joytianya** [comment]
建议使用pt版本：https://huggingface.co/ClueAI/ChatYuan-large-v2

**Comment by a0ge0a** [comment]
好的，感谢！
