### ISSUE TITLE
关于distributed训练的问题

### ISSUE THREAD

**Issue by Tian14267** [clue-ai/ChatYuan#47]
大神你好。我在实验`distributed-training`的代码进行分布式多卡训练的时候，提示这个问题：
```
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    hvd.init()
AttributeError: module 'horovod.torch' has no attribute 'init'

```
请问这个是啥情况啊

我的环境：
horovod == 0.23.0
torch == 2.0.0

**Comment by Tian14267** [comment]
init  问题解决。但是遇到新问题。
训练过程中，设置了双卡训练，但是只有一张卡的训练。这个是啥情况啊

**Comment by joytianya** [comment]
@vaas1993 帮忙看看

**Comment by Tian14267** [comment]
> @vaas1993 帮忙看看

咦，好像可以了。已经解决。谢谢大佬

**Comment by xiaoToby** [comment]
> init 问题解决。但是遇到新问题。 训练过程中，设置了双卡训练，但是只有一张卡的训练。这个是啥情况啊

怎么解决的呢？
