### ISSUE TITLE
经常转圈卡死是什么情况？

### ISSUE THREAD

**Issue by fingertap** [clue-ai/ChatYuan#5]
随便问一些问题就会卡死，应该不是拥塞的原因，因为问他一些基础的问题是秒答的，比如can you understand english，这是能理解的，但是问个复杂点的问题例如：帮我写一个正则表达式，可以从字符串中抽取出连续的数字，就直接卡死了。

**Comment by huangtao36** [comment]
我这不会卡死！

输出：帮我写一个正则表达式，可以从字符串中抽取出连续的数字，然后用正则表达式把数字从字符串中清除掉。用字符串的长度和数字的数字组成，然后去掉正则，把数字全部清除掉然后使用字符串的字符串值。

有点傻，感觉远不及chatGPT

**Comment by joytianya** [comment]
小元还在持续进化中，能力也会越来越好，希望随着它的成长给大家带来更好的体验
