### ISSUE TITLE
'<class 'transformers.models.t5.configuration_t5.T5Config'>' is already used by a Transformers model

### ISSUE THREAD

**Issue by liuxindtc** [clue-ai/ChatYuan#59]
demo error，Thanks
<img width="1327" alt="image" src="https://github.com/clue-ai/ChatYuan/assets/5426932/1201b17b-2643-4250-ae34-427cfb2b0dd8">

**Comment by joytianya** [comment]
已修正，再试试看

**Comment by liuxindtc** [comment]
hi，我是在colab中运行的。刚才试了下，pip install同样没问题，但是python代码执行还是报这个错误。

**Comment by joytianya** [comment]
可以先使用
高级参数配置方式
试试看

**Comment by ZhaoKangkang0572** [comment]
@liuxindtc 
你好，换一个版本的transformers吧，我们当时发布的时候，transformers的发布版本还没有这么新，所以用了从git安装的方式，
现在应该是最新版本的有冲突，所以可以不用那么新的版本，直接
!pip install transformers    （现时间点的版本是4.30.2）
或者安装稍微更低一点的版本
4.29.1 works.

解决方法：
把下面的
!git clone https://github.com/huggingface/transformers.git
!pip install ./transformers

替换为
!pip install transformers
或者更低版本
!pip install transformers==4.29.1

**Comment by liuxindtc** [comment]
> @liuxindtc 你好，换一个版本的transformers吧，我们当时发布的时候，transformers的发布版本还没有这么新，所以用了从git安装的方式， 现在应该是最新版本的有冲突，所以可以不用那么新的版本，直接 !pip install transformers （现时间点的版本是4.30.2） 或者安装稍微更低一点的版本 4.29.1 works.
> 
> 解决方法： 把下面的 !git clone https://github.com/huggingface/transformers.git !pip install ./transformers
> 
> 替换为 !pip install transformers 或者更低版本 !pip install transformers==4.29.1

感谢，的确是这个原因。
之前，我也有点奇怪，本地跑的时候因为我是下载后加载本地，也没有问题。就是colab拉远端出现问题了。原来是transformers的问题。刚才看了下本地是4.27.1
