### ISSUE TITLE
做得太差劲了

### ISSUE THREAD

**Issue by mzhaoshuai** [clue-ai/ChatYuan#7]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/22476764/217747804-e1f7bdc4-6b89-4804-8455-26ee4da4faa0.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/22476764/217747835-208bdbcc-bdee-46d5-b447-b30eb58f331c.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/22476764/217747856-139ec9b6-6335-4378-96a6-75062b63ab86.png">

**Comment by joytianya** [comment]
这些任务还比较弱，还在进化中

**Comment by mzhaoshuai** [comment]
还带改标题嘛。。。

**Comment by ZeyuTeng96** [comment]
> 还带改标题嘛。。。

所以这个repo的issue很有意思
